version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: nebrass/sample-jvm:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
